// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Optica.Api.Datos;

#nullable disable

namespace Optica.Api.Datos.Migraciones
{
    [DbContext(typeof(OpticaDbContext))]
    [Migration("20261009020858_CatalogoYConfiguracion")]
    partial class CatalogoYConfiguracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Optica.Api.Acceso.EstadoAcceso", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("BloqueadoHasta")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashContrasena")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelloSeguridad")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Acceso", null, t =>
                        {
                            t.HasCheckConstraint("CK_Acceso_Unica", "Id = 1");
                        });
                });

            modelBuilder.Entity("Optica.Api.Catalogo.Articulo", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoProveedor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DescripcionBusqueda")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("Margen")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PrecioCosto")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PrecioVenta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Codigo");

                    b.HasIndex("DescripcionBusqueda");

                    b.HasIndex("ProveedorId", "CodigoProveedor")
                        .IsUnique();

                    b.ToTable("Articulos", (string)null);
                });

            modelBuilder.Entity("Optica.Api.Catalogo.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreClave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NombreClave")
                        .IsUnique();

                    b.ToTable("Proveedores", (string)null);
                });

            modelBuilder.Entity("Optica.Api.Configuracion.ParametrosNegocio", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AlicuotaIva")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CondicionFiscal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<long?>("MargenPredeterminado")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MultiploRedondeo")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TopeIdentificacion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Configuracion", null, t =>
                        {
                            t.HasCheckConstraint("CK_Configuracion_Unica", "Id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlicuotaIva = 2100L,
                            CondicionFiscal = "ResponsableInscripto",
                            MultiploRedondeo = 1L,
                            TopeIdentificacion = 1000000000L
                        });
                });

            modelBuilder.Entity("Optica.Api.Catalogo.Articulo", b =>
                {
                    b.HasOne("Optica.Api.Catalogo.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });
#pragma warning restore 612, 618
        }
    }
}
