// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Optica.Api.Datos;

#nullable disable

namespace Optica.Api.Datos.Migraciones
{
    [DbContext(typeof(OpticaDbContext))]
    [Migration("20261009022706_Presupuestos")]
    partial class Presupuestos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Optica.Api.Acceso.EstadoAcceso", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("BloqueadoHasta")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashContrasena")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelloSeguridad")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Acceso", null, t =>
                        {
                            t.HasCheckConstraint("CK_Acceso_Unica", "Id = 1");
                        });
                });

            modelBuilder.Entity("Optica.Api.Catalogo.Articulo", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoProveedor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DescripcionBusqueda")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("Margen")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PrecioCosto")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PrecioVenta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Codigo");

                    b.HasIndex("DescripcionBusqueda");

                    b.HasIndex("ProveedorId", "CodigoProveedor")
                        .IsUnique();

                    b.ToTable("Articulos", (string)null);
                });

            modelBuilder.Entity("Optica.Api.Catalogo.FilaImportacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoProveedor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportacionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroFila")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Razon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportacionId");

                    b.ToTable("FilasImportacion", (string)null);
                });

            modelBuilder.Entity("Optica.Api.Catalogo.Importacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Actualizados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Creados")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("NoProcesados")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Importaciones", (string)null);
                });

            modelBuilder.Entity("Optica.Api.Catalogo.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreClave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NombreClave")
                        .IsUnique();

                    b.ToTable("Proveedores", (string)null);
                });

            modelBuilder.Entity("Optica.Api.Configuracion.ParametrosNegocio", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AlicuotaIva")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CondicionFiscal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<long?>("MargenPredeterminado")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MultiploRedondeo")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TopeIdentificacion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Configuracion", null, t =>
                        {
                            t.HasCheckConstraint("CK_Configuracion_Unica", "Id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlicuotaIva = 2100L,
                            CondicionFiscal = "ResponsableInscripto",
                            MultiploRedondeo = 1L,
                            TopeIdentificacion = 1000000000L
                        });
                });

            modelBuilder.Entity("Optica.Api.Presupuestos.LineaPresupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticuloCodigo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("Descuento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PrecioConDescuento")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PrecioFinal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PrecioUnitario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PresupuestoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PresupuestoId");

                    b.ToTable("LineasPresupuesto", (string)null);
                });

            modelBuilder.Entity("Optica.Api.Presupuestos.Presupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApellidoBusqueda")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreBusqueda")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<long>("Total")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Presupuestos", (string)null);
                });

            modelBuilder.Entity("Optica.Api.Catalogo.Articulo", b =>
                {
                    b.HasOne("Optica.Api.Catalogo.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Optica.Api.Catalogo.FilaImportacion", b =>
                {
                    b.HasOne("Optica.Api.Catalogo.Importacion", null)
                        .WithMany("Filas")
                        .HasForeignKey("ImportacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Optica.Api.Catalogo.Importacion", b =>
                {
                    b.HasOne("Optica.Api.Catalogo.Proveedor", null)
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Optica.Api.Presupuestos.LineaPresupuesto", b =>
                {
                    b.HasOne("Optica.Api.Presupuestos.Presupuesto", null)
                        .WithMany("Lineas")
                        .HasForeignKey("PresupuestoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Optica.Api.Catalogo.Importacion", b =>
                {
                    b.Navigation("Filas");
                });

            modelBuilder.Entity("Optica.Api.Presupuestos.Presupuesto", b =>
                {
                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
